/*
 Generated by typeshare 1.9.2
*/

export interface ShortenedUrl {
  short_url: string
  target_url: string
  comment?: string
  active: boolean
}

export type AllShortenedUrls = ShortenedUrl[]

export interface CreateShortenedUrlDto {
  short_url: string
  target_url: string
  comment?: string
}

export interface DeleteShortenedUrlDto {
  short_url: string
}
